server/cart/urls.py
from django.urls import path
from .views import (
    PurchaseListView, PurchaseCreateView, cart_view
)


app_name = 'cart'

urlpatterns = [
    path('create/', PurchaseCreateView.as_view(), name='create'),
    path('list/', PurchaseListView.as_view(), name='list'),
    path('', cart_view, name='cart'),
]

server/main/urls.py
from django.urls import path

from main.views import (
    main, contacts, about
)

app_name = 'main'

urlpatterns = [
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('', main, name='index'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings

from rest_framework.routers import DefaultRouter
from debug_toolbar import urls as debug_urls

from products.viewsets import (
    CategoryViewSet, ProductViewSet
)


router = DefaultRouter()
router.register('categories', CategoryViewSet, base_name='categories')
router.register('products', ProductViewSet, base_name='products')

django_router = [
    path('products/', include('products.routes')),
    path('categories/', include('products.routes.categories'))
]

urlpatterns = [
    path('api/', include((router.urls, 'rest'))),
    path('django_api/', include(django_router)),
    path('admin/', admin.site.urls),
    re_path(
        r'^auth/verify/google/oauth2/',
        include(
            'social_django.urls',
            namespace='social'
        ),
    ),
    path('products/', include('products.urls')),
    path('categories/', include('products.urls.categories')),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_urls))]

server/server/templates/form.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% for err in form.not_field_errors %}
    <div class="alert alert-danger" role="alert">
        <span>{{ err}}</span>
    </div>
    {% endfor %}

    {% for field in form %}
    <div class="field-group">
        <label for="{{ form.name }}">{{ field.label }}</label>
        {{ field }}

        {% for err in field.errors %}
        <small class="field__error">{{ err }}</small>
        {% endfor %}
    </div>
    {% endfor %}

    <input type="submit">
</form>

server/server/templates/formset.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ formset.management_form }} 
    {% for err in form.not_field_errors %}
    <div class="alert alert-danger" role="alert">
        <span>{{ err}}</span>
    </div>
    {% endfor %}
    {% for field in form %}
    <div class="field-group">
        <label for="{{ form.name }}">{{ field.label }}</label>
        {{ field }}
    
        {% for err in field.errors %}
        <small class="field__error">{{ err }}</small>
        {% endfor %}
    </div>
    {% endfor %}
    {% for form in formset %}
    <fieldset>        
        {% for field in form %}
        <div class="field-group">
            <label for="{{ form.name }}">{{ field.label }}</label>
            {{ field }}
        
            {% for err in field.errors %}
            <small class="field__error">{{ err }}</small>
            {% endfor %}
        </div>
        {% endfor %}
    </fieldset>

    {% endfor %}
    <input type="submit">
</form>

server/server/templates/master.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>
        {% block page_title %}
        {% endblock %}
    </title>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <script src="{% static 'assets/js/bootstrap.bundle.js' %}"></script>
    {% block page_styles %}
    {% endblock %}
</head>
<body>
    <ul class="menu">
        <li class="menu__link">
            <a href="{% url 'main:index' %}" class="menu__link-inner_main">Main</a>
        </li>
        <li class="menu__link">
            <a href="{% url 'products:list' %}" class="menu__link-inner_products">Products</a>
        </li>
        <li class="menu__link">
            <a href="{% url 'categories:list' %}" class="menu__link-inner_categories">Categories</a>
        </li>
        <li class="menu__link">
            <a href="{% url 'main:contacts' %}" class="menu__link-inner_contacts">Contacts</a>
        </li>
        <li class="menu__link">
            <a href="{% url 'main:about' %}" class="menu__link-inner_about">About</a>
        </li>
    </ul>
    <ul class="category-list">
        {% for itm in categories %}
        <li class="category-item">
            <a class="category-item__link" href="{% url 'categories:detail' pk=itm.id %}">
                {{ itm }}
            </a>
    
        </li>
        {% endfor %}
    </ul>
    <section class="container">
        {% block page_content %}
        {% endblock %}
    </section>
    {% block page_js %}
    {% endblock %}
</body>
</html>

server/server/templates/pagination.html
<ul class="pagination">
    {% if page.has_previous %}
    <li class="pagination__link_prev">
        <a href="?page={{ page.previous_page_number }}">
            Previous
        </a>
    </li>
    {% endif %}
    {% for num in paginator.page_range %}
    <li class="pagination__link_page">
        <a href="?page={{ num }}">
            {{ num }}
        </a>
    </li>
    {% endfor %}
    {% if page.has_next %}
    <li class="pagination__link_next">
        <a href="?page={{ page.next_page_number }}">
            Next
        </a>
    </li>
    {% endif %}
</ul>